using TfsReviewPlatform.Application.Models;
using TfsReviewPlatform.Application.Services;

namespace TfsReviewPlatform.Tests;

public sealed class DiffPreprocessorTests
{
    [Fact]
    public void Process_FiltersIgnoredExtensions_AndBuildsChunks()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 80
        }));

        var diff = """
            diff --git a/src/App/Service.cs b/src/App/Service.cs
            +++ b/src/App/Service.cs
            @@ -1,1 +1,3 @@
            +public class Service {}
            diff --git a/src/App/logo.png b/src/App/logo.png
            +++ b/src/App/logo.png
            @@ -0,0 +1 @@
            +binary
            diff --git a/tests/App/ServiceTests.cs b/tests/App/ServiceTests.cs
            +++ b/tests/App/ServiceTests.cs
            @@ -1,1 +1,3 @@
            +public class ServiceTests {}
            """;

        var result = sut.Process(diff);

        Assert.Contains("src/App/Service.cs", result.ChangedFiles);
        Assert.Contains("tests/App/ServiceTests.cs", result.ChangedFiles);
        Assert.DoesNotContain("src/App/logo.png", result.ChangedFiles);
        Assert.NotEmpty(result.Chunks);
    }

    [Fact]
    public void Process_SplitsOversizedSingleFileDiffIntoMultipleChunks()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 120
        }));

        var longPayload = new string('x', 420);
        var alphaLines = string.Join('\n', Enumerable.Range(1, 5).Select(index => $"+line {index:00} {longPayload}"));
        var betaLines = string.Join('\n', Enumerable.Range(6, 5).Select(index => $"+line {index:00} {longPayload}"));
        var diff = $"""
            diff --git a/src/App/HugeFile.cs b/src/App/HugeFile.cs
            +++ b/src/App/HugeFile.cs
            @@ -1,1 +1,6 @@
            {alphaLines}
            @@ -10,1 +15,6 @@
            {betaLines}
            """;

        var result = sut.Process(diff);

        Assert.True(result.Chunks.Count >= 2);
        Assert.All(result.Chunks, chunk => Assert.Contains("## File: 'src/App/HugeFile.cs'", chunk, StringComparison.Ordinal));
        Assert.All(result.Chunks, chunk => Assert.Contains("__new hunk__", chunk, StringComparison.Ordinal));
    }

    [Fact]
    public void Process_KeepsDeletionOnlyHunksInArtifacts_ButRemovesThemFromReviewContext()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 1000
        }));

        var diff = """
            diff --git a/src/App/Service.cs b/src/App/Service.cs
            --- a/src/App/Service.cs
            +++ b/src/App/Service.cs
            @@ -1,3 +1,0 @@
            -old line 1
            -old line 2
            -old line 3
            @@ -10,2 +7,3 @@
             context
            +new line 1
            +new line 2
            """;

        var result = sut.Process(diff);

        Assert.Contains("-old line 1", result.FilteredDiffText);
        Assert.DoesNotContain("-old line 1", result.ReviewContextDiffText);
        Assert.Contains("+new line 1", result.ReviewContextDiffText);
        Assert.Single(result.Chunks);
    }

    [Fact]
    public void Process_ExcludesGeneratedAndWsdlFilesOnlyFromReviewContext()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 1000
        }));

        var diff = """
            diff --git a/src/App/Connected Services/LegacyApi/Reference.cs b/src/App/Connected Services/LegacyApi/Reference.cs
            --- a/src/App/Connected Services/LegacyApi/Reference.cs
            +++ b/src/App/Connected Services/LegacyApi/Reference.cs
            @@ -1,2 +1,3 @@
            +// <auto-generated>
            +public partial class ReferenceClient {}
            diff --git a/contracts/legacy.wsdl b/contracts/legacy.wsdl
            --- a/contracts/legacy.wsdl
            +++ b/contracts/legacy.wsdl
            @@ -1,1 +1,2 @@
            +<definitions />
            diff --git a/src/App/RealService.cs b/src/App/RealService.cs
            --- a/src/App/RealService.cs
            +++ b/src/App/RealService.cs
            @@ -1,1 +1,2 @@
            +public class RealService {}
            """;

        var result = sut.Process(diff);

        Assert.Contains("Connected Services/LegacyApi/Reference.cs", result.FilteredDiffText);
        Assert.Contains("contracts/legacy.wsdl", result.FilteredDiffText);
        Assert.DoesNotContain("Connected Services/LegacyApi/Reference.cs", result.ReviewContextDiffText);
        Assert.DoesNotContain("contracts/legacy.wsdl", result.ReviewContextDiffText);
        Assert.Contains("RealService.cs", result.ReviewContextDiffText);
    }

    [Fact]
    public void Process_FormatsChunksForStructuredReviewConsumption()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 4000
        }));

        var diff = """
            diff --git a/src/App/Service.cs b/src/App/Service.cs
            --- a/src/App/Service.cs
            +++ b/src/App/Service.cs
            @@ -10,2 +10,3 @@ public async Task Handle()
             existing line
            +new line 1
            +new line 2
            -old line 1
            """;

        var result = sut.Process(diff);

        var chunk = Assert.Single(result.Chunks);
        Assert.Contains("## File: 'src/App/Service.cs'", chunk);
        Assert.Contains("__new hunk__", chunk);
        Assert.Contains("__old hunk__", chunk);
        Assert.Contains("Context: public async Task Handle()", chunk);
        Assert.Contains("  10  existing line", chunk);
        Assert.Contains("  11 +new line 1", chunk);
        Assert.Contains("-old line 1", chunk);
    }

    [Fact]
    public void Process_KeepsLargeFileChunksLocalToNearbyHunks()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 220
        }));

        var longPayload = new string('y', 420);
        var alphaLines = string.Join('\n', Enumerable.Range(1, 3).Select(index => $"+alpha {index:00} {longPayload}"));
        var betaLines = string.Join('\n', Enumerable.Range(1, 3).Select(index => $"+beta {index:00} {longPayload}"));
        var diff = $"""
            diff --git a/src/App/HugeFile.cs b/src/App/HugeFile.cs
            --- a/src/App/HugeFile.cs
            +++ b/src/App/HugeFile.cs
            @@ -10,1 +10,4 @@
            {alphaLines}
            @@ -200,1 +203,4 @@
            {betaLines}
            """;

        var result = sut.Process(diff);

        Assert.True(result.Chunks.Count >= 2);
        Assert.Contains(result.Chunks, chunk => chunk.Contains("alpha 01 ", StringComparison.Ordinal));
        Assert.Contains(result.Chunks, chunk => chunk.Contains("beta 01 ", StringComparison.Ordinal));
        Assert.DoesNotContain(
            result.Chunks,
            chunk => chunk.Contains("alpha 01 ", StringComparison.Ordinal) &&
                     chunk.Contains("beta 01 ", StringComparison.Ordinal));
    }

    [Fact]
    public void Process_DoesNotMergePrimaryReviewChunksAcrossDifferentFiles()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxPrimaryReviewChunkCharacters = 10000,
            MaxChunkCharacters = 10000,
            MergePrimaryReviewChunks = false
        }));

        var diff = """
            diff --git a/src/App/First.cs b/src/App/First.cs
            --- a/src/App/First.cs
            +++ b/src/App/First.cs
            @@ -1,1 +1,2 @@
            +public class First {}
            diff --git a/src/App/Second.cs b/src/App/Second.cs
            --- a/src/App/Second.cs
            +++ b/src/App/Second.cs
            @@ -1,1 +1,2 @@
            +public class Second {}
            """;

        var result = sut.Process(diff);

        Assert.Equal(2, result.ReviewChunks.Count);
        Assert.Contains(result.ReviewChunks, chunk => chunk.Contains("## File: 'src/App/First.cs'", StringComparison.Ordinal));
        Assert.Contains(result.ReviewChunks, chunk => chunk.Contains("## File: 'src/App/Second.cs'", StringComparison.Ordinal));
        Assert.DoesNotContain(
            result.ReviewChunks,
            chunk => chunk.Contains("## File: 'src/App/First.cs'", StringComparison.Ordinal) &&
                     chunk.Contains("## File: 'src/App/Second.cs'", StringComparison.Ordinal));
    }

    [Fact]
    public void Process_MergesPrimaryReviewChunksAcrossFiles_WhenEnabled()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxPrimaryReviewChunkCharacters = 10000,
            MaxChunkCharacters = 10000,
            MergePrimaryReviewChunks = true
        }));

        var diff = """
            diff --git a/src/App/First.cs b/src/App/First.cs
            --- a/src/App/First.cs
            +++ b/src/App/First.cs
            @@ -1,1 +1,2 @@
            +public class First {}
            diff --git a/src/App/Second.cs b/src/App/Second.cs
            --- a/src/App/Second.cs
            +++ b/src/App/Second.cs
            @@ -1,1 +1,2 @@
            +public class Second {}
            """;

        var result = sut.Process(diff);

        Assert.Single(result.ReviewChunks);
        Assert.Contains("## File: 'src/App/First.cs'", result.ReviewChunks[0], StringComparison.Ordinal);
        Assert.Contains("## File: 'src/App/Second.cs'", result.ReviewChunks[0], StringComparison.Ordinal);
        Assert.Equal(2, result.Chunks.Count);
    }

    [Fact]
    public void Process_SplitsOversizedFileByWholeHunksAndKeepsStructuredFormat()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 220
        }));

        var longPayload = new string('z', 420);
        var alphaLines = string.Join('\n', Enumerable.Range(1, 3).Select(index => $"+alpha {index:00} {longPayload}"));
        var betaLines = string.Join('\n', Enumerable.Range(1, 3).Select(index => $"+beta {index:00} {longPayload}"));
        var diff = $"""
            diff --git a/src/App/HugeFile.cs b/src/App/HugeFile.cs
            --- a/src/App/HugeFile.cs
            +++ b/src/App/HugeFile.cs
            @@ -10,1 +10,4 @@ public void Alpha()
             old line
            {alphaLines}
            @@ -30,1 +33,4 @@ public void Beta()
             old line
            {betaLines}
            """;

        var result = sut.Process(diff);

        Assert.True(result.Chunks.Count >= 2);
        Assert.All(result.Chunks, chunk => Assert.Contains("## File: 'src/App/HugeFile.cs'", chunk, StringComparison.Ordinal));
        Assert.All(result.Chunks, chunk => Assert.Contains("__new hunk__", chunk, StringComparison.Ordinal));
        Assert.Contains(result.Chunks, chunk => chunk.Contains("Context: public void Alpha()", StringComparison.Ordinal));
        Assert.Contains(result.Chunks, chunk => chunk.Contains("Context: public void Beta()", StringComparison.Ordinal));
        Assert.DoesNotContain(
            result.Chunks,
            chunk => chunk.Contains("alpha 01 1234567890", StringComparison.Ordinal) &&
                     chunk.Contains("beta 01 1234567890", StringComparison.Ordinal));
    }

    [Fact]
    public void Process_GeneratesSqlHints_ForRemovedBusinessFiltersAndUnusedJoin()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 4000
        }));

        var diff = """
            diff --git a/Infrastructure/Db/GetOrderListForExcelFile.sql b/Infrastructure/Db/GetOrderListForExcelFile.sql
            --- a/Infrastructure/Db/GetOrderListForExcelFile.sql
            +++ b/Infrastructure/Db/GetOrderListForExcelFile.sql
            @@ -38,12 +38,10 @@
                     left join "System" sys
                               on o."SystemId" = sys."SystemId"
                     left join "ReplicBranch" rb
                               on o."RegionCode" = rb."RegionIsoCode"
                     left join "OperationReason" opr
                               on o."ReasonId" = opr."ReasonId"
            -where rb."IsBasic" is true
            -  and rb."IsBcAllowed" is true
            -  and (@orderId is null or o."OrderId" = @orderId)
            +where (@orderId is null or o."OrderId" = @orderId)
               and (@msisdn is null or o."Msisdn" = @msisdn)
            """;

        var result = sut.Process(diff);

        Assert.Contains(result.ReviewHints, hint => hint.RuleId == "SQL_REMOVED_BUSINESS_FILTER");
        Assert.Contains(result.ReviewHints, hint => hint.RuleId == "SQL_JOIN_ALIAS_ONLY_USED_IN_JOIN");
        Assert.Contains("Deterministic review hints", result.ReviewChunks[0], StringComparison.Ordinal);
        Assert.Contains("duplicate result rows", result.ReviewChunks[0], StringComparison.Ordinal);
    }

    [Fact]
    public void Process_GeneratesConfigurationHint_WhenOptionsSectionIsNotVisibleInChangedConfig()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 4000
        }));

        var diff = """
            diff --git a/src/App/DI/AddDependencies.cs b/src/App/DI/AddDependencies.cs
            --- a/src/App/DI/AddDependencies.cs
            +++ b/src/App/DI/AddDependencies.cs
            @@ -100,1 +100,2 @@
            +services.Configure<CacheOptions>(configuration.GetSection("CacheOptions"));
            +services.AddHostedService<RegionCacheBackgroundService>();
            diff --git a/src/App/appsettings.json b/src/App/appsettings.json
            --- a/src/App/appsettings.json
            +++ b/src/App/appsettings.json
            @@ -430,1 +430,5 @@
            +  "_Options": {
            +    "RegionCacheTtlMinutes": 1440
            +  }
            """;

        var result = sut.Process(diff);

        var hint = Assert.Single(result.ReviewHints, hint => hint.RuleId == "OPTIONS_SECTION_NOT_VISIBLE_IN_CHANGED_CONFIG");
        Assert.Equal("src/App/DI/AddDependencies.cs", hint.FilePath);
        Assert.Contains("CacheOptions", hint.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Process_GeneratesTestSeedHint_WhenChangedTestUsesSeedConstant()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 4000
        }));

        var diff = """
            diff --git a/tests/App/GetOrdersFileTests.cs b/tests/App/GetOrdersFileTests.cs
            --- a/tests/App/GetOrdersFileTests.cs
            +++ b/tests/App/GetOrdersFileTests.cs
            @@ -60,2 +60,3 @@
            +query.RegionCode = new List<string> { SeedReplicBranchTable.RustRegionCode };
            +order.OrderRegionName.Should().Be(SeedReplicBranchTable.RustRegionName);
            """;

        var result = sut.Process(diff);

        Assert.Contains(result.ReviewHints, hint =>
            hint.RuleId == "TEST_ASSERTION_USES_SEED_MEMBER" &&
            hint.Message.Contains("SeedReplicBranchTable.RustRegionCode", StringComparison.Ordinal));
    }

    [Fact]
    public void Process_GeneratesDataIntegrityHint_ForGroupByFirstWithoutOrder()
    {
        var sut = new DiffPreprocessor(Microsoft.Extensions.Options.Options.Create(new ReviewPipelineOptions
        {
            MaxChunkCharacters = 4000
        }));

        var diff = """
            diff --git a/src/App/RegionCacheRepository.cs b/src/App/RegionCacheRepository.cs
            --- a/src/App/RegionCacheRepository.cs
            +++ b/src/App/RegionCacheRepository.cs
            @@ -100,1 +100,8 @@
            +var newCache = regions
            +    .GroupBy(r => r.RegionCode, StringComparer.OrdinalIgnoreCase)
            +    .ToFrozenDictionary(
            +        g => g.Key,
            +        g => g.First(),
            +        StringComparer.OrdinalIgnoreCase);
            """;

        var result = sut.Process(diff);

        Assert.Contains(result.ReviewHints, hint => hint.RuleId == "GROUP_BY_FIRST_WITHOUT_ORDER");
    }

}
